/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OmSommarRouteImport } from './routes/om-sommar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BeloningarRouteImport } from './routes/beloningar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FTokenRouteImport } from './routes/f.$token'
import { Route as ChildNameRouteImport } from './routes/child.$name'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ChildNameIndexRouteImport } from './routes/child.$name.index'
import { Route as ChildNameRewardsRouteImport } from './routes/child.$name.rewards'
import { Route as ChildNameHistoryRouteImport } from './routes/child.$name.history'
import { Route as ChildNameFavoritesRouteImport } from './routes/child.$name.favorites'
import { Route as ChildNameCalendarRouteImport } from './routes/child.$name.calendar'
import { Route as ChildNameBucketlistRouteImport } from './routes/child.$name.bucketlist'

const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OmSommarRoute = OmSommarRouteImport.update({
  id: '/om-sommar',
  path: '/om-sommar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BeloningarRoute = BeloningarRouteImport.update({
  id: '/beloningar',
  path: '/beloningar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FTokenRoute = FTokenRouteImport.update({
  id: '/f/$token',
  path: '/f/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildNameRoute = ChildNameRouteImport.update({
  id: '/child/$name',
  path: '/child/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildNameIndexRoute = ChildNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChildNameRoute,
} as any)
const ChildNameRewardsRoute = ChildNameRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => ChildNameRoute,
} as any)
const ChildNameHistoryRoute = ChildNameHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ChildNameRoute,
} as any)
const ChildNameFavoritesRoute = ChildNameFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => ChildNameRoute,
} as any)
const ChildNameCalendarRoute = ChildNameCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ChildNameRoute,
} as any)
const ChildNameBucketlistRoute = ChildNameBucketlistRouteImport.update({
  id: '/bucketlist',
  path: '/bucketlist',
  getParentRoute: () => ChildNameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beloningar': typeof BeloningarRoute
  '/login': typeof LoginRoute
  '/om-sommar': typeof OmSommarRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/child/$name': typeof ChildNameRouteWithChildren
  '/f/$token': typeof FTokenRoute
  '/child/$name/bucketlist': typeof ChildNameBucketlistRoute
  '/child/$name/calendar': typeof ChildNameCalendarRoute
  '/child/$name/favorites': typeof ChildNameFavoritesRoute
  '/child/$name/history': typeof ChildNameHistoryRoute
  '/child/$name/rewards': typeof ChildNameRewardsRoute
  '/child/$name/': typeof ChildNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beloningar': typeof BeloningarRoute
  '/login': typeof LoginRoute
  '/om-sommar': typeof OmSommarRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/f/$token': typeof FTokenRoute
  '/child/$name/bucketlist': typeof ChildNameBucketlistRoute
  '/child/$name/calendar': typeof ChildNameCalendarRoute
  '/child/$name/favorites': typeof ChildNameFavoritesRoute
  '/child/$name/history': typeof ChildNameHistoryRoute
  '/child/$name/rewards': typeof ChildNameRewardsRoute
  '/child/$name': typeof ChildNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beloningar': typeof BeloningarRoute
  '/login': typeof LoginRoute
  '/om-sommar': typeof OmSommarRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/child/$name': typeof ChildNameRouteWithChildren
  '/f/$token': typeof FTokenRoute
  '/child/$name/bucketlist': typeof ChildNameBucketlistRoute
  '/child/$name/calendar': typeof ChildNameCalendarRoute
  '/child/$name/favorites': typeof ChildNameFavoritesRoute
  '/child/$name/history': typeof ChildNameHistoryRoute
  '/child/$name/rewards': typeof ChildNameRewardsRoute
  '/child/$name/': typeof ChildNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beloningar'
    | '/login'
    | '/om-sommar'
    | '/onboarding'
    | '/parent'
    | '/auth/callback'
    | '/child/$name'
    | '/f/$token'
    | '/child/$name/bucketlist'
    | '/child/$name/calendar'
    | '/child/$name/favorites'
    | '/child/$name/history'
    | '/child/$name/rewards'
    | '/child/$name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beloningar'
    | '/login'
    | '/om-sommar'
    | '/onboarding'
    | '/parent'
    | '/auth/callback'
    | '/f/$token'
    | '/child/$name/bucketlist'
    | '/child/$name/calendar'
    | '/child/$name/favorites'
    | '/child/$name/history'
    | '/child/$name/rewards'
    | '/child/$name'
  id:
    | '__root__'
    | '/'
    | '/beloningar'
    | '/login'
    | '/om-sommar'
    | '/onboarding'
    | '/parent'
    | '/auth/callback'
    | '/child/$name'
    | '/f/$token'
    | '/child/$name/bucketlist'
    | '/child/$name/calendar'
    | '/child/$name/favorites'
    | '/child/$name/history'
    | '/child/$name/rewards'
    | '/child/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeloningarRoute: typeof BeloningarRoute
  LoginRoute: typeof LoginRoute
  OmSommarRoute: typeof OmSommarRoute
  OnboardingRoute: typeof OnboardingRoute
  ParentRoute: typeof ParentRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ChildNameRoute: typeof ChildNameRouteWithChildren
  FTokenRoute: typeof FTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-sommar': {
      id: '/om-sommar'
      path: '/om-sommar'
      fullPath: '/om-sommar'
      preLoaderRoute: typeof OmSommarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beloningar': {
      id: '/beloningar'
      path: '/beloningar'
      fullPath: '/beloningar'
      preLoaderRoute: typeof BeloningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$token': {
      id: '/f/$token'
      path: '/f/$token'
      fullPath: '/f/$token'
      preLoaderRoute: typeof FTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/$name': {
      id: '/child/$name'
      path: '/child/$name'
      fullPath: '/child/$name'
      preLoaderRoute: typeof ChildNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/$name/': {
      id: '/child/$name/'
      path: '/'
      fullPath: '/child/$name/'
      preLoaderRoute: typeof ChildNameIndexRouteImport
      parentRoute: typeof ChildNameRoute
    }
    '/child/$name/rewards': {
      id: '/child/$name/rewards'
      path: '/rewards'
      fullPath: '/child/$name/rewards'
      preLoaderRoute: typeof ChildNameRewardsRouteImport
      parentRoute: typeof ChildNameRoute
    }
    '/child/$name/history': {
      id: '/child/$name/history'
      path: '/history'
      fullPath: '/child/$name/history'
      preLoaderRoute: typeof ChildNameHistoryRouteImport
      parentRoute: typeof ChildNameRoute
    }
    '/child/$name/favorites': {
      id: '/child/$name/favorites'
      path: '/favorites'
      fullPath: '/child/$name/favorites'
      preLoaderRoute: typeof ChildNameFavoritesRouteImport
      parentRoute: typeof ChildNameRoute
    }
    '/child/$name/calendar': {
      id: '/child/$name/calendar'
      path: '/calendar'
      fullPath: '/child/$name/calendar'
      preLoaderRoute: typeof ChildNameCalendarRouteImport
      parentRoute: typeof ChildNameRoute
    }
    '/child/$name/bucketlist': {
      id: '/child/$name/bucketlist'
      path: '/bucketlist'
      fullPath: '/child/$name/bucketlist'
      preLoaderRoute: typeof ChildNameBucketlistRouteImport
      parentRoute: typeof ChildNameRoute
    }
  }
}

interface ChildNameRouteChildren {
  ChildNameBucketlistRoute: typeof ChildNameBucketlistRoute
  ChildNameCalendarRoute: typeof ChildNameCalendarRoute
  ChildNameFavoritesRoute: typeof ChildNameFavoritesRoute
  ChildNameHistoryRoute: typeof ChildNameHistoryRoute
  ChildNameRewardsRoute: typeof ChildNameRewardsRoute
  ChildNameIndexRoute: typeof ChildNameIndexRoute
}

const ChildNameRouteChildren: ChildNameRouteChildren = {
  ChildNameBucketlistRoute: ChildNameBucketlistRoute,
  ChildNameCalendarRoute: ChildNameCalendarRoute,
  ChildNameFavoritesRoute: ChildNameFavoritesRoute,
  ChildNameHistoryRoute: ChildNameHistoryRoute,
  ChildNameRewardsRoute: ChildNameRewardsRoute,
  ChildNameIndexRoute: ChildNameIndexRoute,
}

const ChildNameRouteWithChildren = ChildNameRoute._addFileChildren(
  ChildNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeloningarRoute: BeloningarRoute,
  LoginRoute: LoginRoute,
  OmSommarRoute: OmSommarRoute,
  OnboardingRoute: OnboardingRoute,
  ParentRoute: ParentRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ChildNameRoute: ChildNameRouteWithChildren,
  FTokenRoute: FTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
